name: Codecov

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C link-dead-code"

jobs:
  call_codecov_workflow:
    uses: banyancomputer/.github/workflow-templates/codecov.yml@master
    with:
      name_of_stuff_to_test_in_target: 'ipfs_proof_buddy'
